### ISSUE TITLE
[FATAL tini (7)] exec /init failed: Exec format error

### ISSUE THREAD

**Issue by Warvf** [arsenicks/pyhydroquebec-hass-addons#1]
I'm pretty new to HA and saw that add-on work you did. Can't get it to run though. Getting an error : [FATAL tini (7)] exec /init failed: Exec format error.

**Comment by arsenicks** [comment]
Hi, thanks for reporting your issue. First just doublecheck that you have created the pyhq-config.yaml file in the config directory and then you have configured all the information required in the "Config" tab of the addon. The second thing to try is just uninstall, and go into the add on store, in the verical "..." on the top right hit reload, and then try to reinstall the addon just to be sure.

If this doesn't fix your issue, could you provide more information on your setup please ?

Where hass is running ? Ex. RaspberryPi, virtual machine, x86_64 etc..
What version of hass are you running ?

I suspect you are running on ARM and I didn't build image for this architecture yet. The code is pretty much a test for now, I'll have to change the way I build image and automate everything.

**Comment by Warvf** [comment]
All configuration is done. I'm using rpi4 so yeah arm64

**Comment by arsenicks** [comment]
That's it, unfortunately in the very short term, I don't have a fix.

I realized I've used an hassio image to build the current image and those are deprecated, so I'm currently reading on how to do it correctly.. Once it's done, I will be able to generate container images for all arch.

I'll let this issue open and let you know when it's ready!

Thanks for your feedback

FYI, I just pushed a change to remove the ARM from the supported arch.

**Comment by arsenicks** [comment]
Whoa it closed the issue, didn't know it will do that.

Could you try to update the add-on and retest please ? Version should be 0.1 now.

Let me know if it works!

**Comment by Warvf** [comment]
Still the same error. Looks like it is still version 0.024 even after a fresh install. Any clue?

**Comment by Warvf** [comment]
Just got the update and it works! Thanks 
Next up winter credit PR? 😁

**Comment by arsenicks** [comment]
Great, good news!

You're talking about https://github.com/titilambert/pyhydroquebec/issues/61 ? My knowledge in python is pretty basic, I'm afraid I will be of no help to fix this. But as far as I can tell @tech165 did a PR to add this feature: https://github.com/titilambert/pyhydroquebec/pull/63 it just never got accepted, like most PR on the project... The last pull requested merged date back to january 24, nothing since then

Do we know if the owner of the project still alive/maintaining this project ? His last comment date from january 24 too: https://github.com/titilambert/pyhydroquebec/pull/60#issuecomment-766437460
